FROM node:18

ARG DB_HOST
ARG DB_PORT
ARG DB_NAME
ARG DB_USER
ARG DB_PASS
ARG APP_ENV
ARG APP_PORT
ARG JWT_SECRET
ARG PAGE_SIZE
ARG CRYPTO_SECRET_KEY
ARG CRYPTO_IV_KEY
ARG SENTRY_DSN
ARG ORIGIN_URL
ARG KEYCLOAK_URL
ARG ROOT_DOMAIN
ARG REALM_NAME
ARG KEYCLOAK_ADMIN_NAME
ARG KEYCLOAK_GRANT_TYPE
ARG KEYCLOAK_ADMIN_CLIENT_ID
ARG USER_CLIENT_ID
ARG MASTER_REALM
ARG KEYCLOAK_LOGIN_THEME
ARG HTTP_PROXY
ARG KEYCLOAK_ADMIN_PASSWORD
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG AWS_BUCKET_NAME
ARG TZ
ARG DAILY_STORY_COMMUNICATION_URL
ARG DAILY_STORY_API_TOKEN
ARG DAILY_STORY_CAMPAIGN_ID
ARG DAILY_STORY_D37_key
ARG DAILY_STORY_ENABLED
ARG ENABLE_CONTAMINATION_ALERTS
ARG TWILIO_ACCOUNT_SID
ARG TWILIO_AUTH_TOKEN
ARG TWILIO_PHONE_NUMBER
ARG TWILIO_API_SECRET
ARG TWILIO_API_KEY
ARG TWILIO_TWIML_APP_SID


RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY --chown=node . .
RUN yarn install
CMD ["yarn", "start"]

