#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "************************************ Running Tests Please Wait ************************************"
yarn --silent --version >/dev/null 2>&1 && yarn test:cov && yarn lint
